[package]
name = "example"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"
publish = false

[dependencies]
butane = { path="../butane"}

[package.metadata.release]
release = false