[package]
name = "example"
version = "0.1.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition.workspace = true
publish = false
build = "build.rs"

[dependencies]
butane = { path = "../butane" }

[package.metadata.release]
release = false
