version = 1
test_patterns = [
  "butane/tests/**", 
  "butane_core/tests/**", 
  "example/tests/**",
]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
enabled = true
name = "test-coverage"
