CREATE TABLE a (
"id" INTEGER NOT NULL PRIMARY KEY
);
CREATE TABLE b (
"id" INTEGER NOT NULL PRIMARY KEY
);
CREATE TABLE b_many_a_Many (
"owner" INTEGER NOT NULL,
has INTEGER NOT NULL
);
ALTER TABLE b_many_a_Many ADD FOREIGN KEY ("owner") REFERENCES b("id");
ALTER TABLE b_many_a_Many ADD FOREIGN KEY (has) REFERENCES a("id");
