CREATE TABLE Post_tags_Many (
"owner" BYTEA NOT NULL,
has TEXT NOT NULL
);
CREATE TABLE "Tag" (
"tag" TEXT NOT NULL PRIMARY KEY
);
ALTER TABLE Post DROP COLUMN tags;
ALTER TABLE Post_tags_Many ADD FOREIGN KEY ("owner") REFERENCES Post("id");
ALTER TABLE Post_tags_Many ADD FOREIGN KEY (has) REFERENCES "Tag"("tag");
