CREATE TABLE Blog (
`id` VARBINARY(255) NOT NULL PRIMARY KEY,
`name` TEXT NOT NULL
);
CREATE TABLE Post (
`id` VARBINARY(255) NOT NULL PRIMARY KEY,
title TEXT NOT NULL,
body TEXT NOT NULL,
published BOOLEAN NOT NULL,
blog VARBINARY(255) NOT NULL,
byline TEXT,
likes INT NOT NULL
);
CREATE TABLE Post_tags_Many (
`owner` VARBINARY(255) NOT NULL,
has VARCHAR(255) NOT NULL
);
CREATE TABLE `Tag` (
`tag` VARCHAR(255) NOT NULL PRIMARY KEY
);
ALTER TABLE Post ADD CONSTRAINT Post_blog_fkey FOREIGN KEY (blog) REFERENCES Blog(`id`);
ALTER TABLE Post_tags_Many ADD CONSTRAINT Post_tags_Many_owner_fkey FOREIGN KEY (`owner`) REFERENCES Post(`id`);
ALTER TABLE Post_tags_Many ADD CONSTRAINT Post_tags_Many_has_fkey FOREIGN KEY (has) REFERENCES `Tag`(`tag`);
CREATE TABLE IF NOT EXISTS butane_migrations (
`name` VARCHAR(255) NOT NULL PRIMARY KEY
);
