CREATE TABLE Blog (
"id" BLOB NOT NULL PRIMARY KEY,
"name" TEXT NOT NULL
) STRICT;
CREATE TABLE Post (
"id" BLOB NOT NULL PRIMARY KEY,
title TEXT NOT NULL,
body TEXT NOT NULL,
published INTEGER NOT NULL,
blog BLOB NOT NULL,
byline TEXT,
likes INTEGER NOT NULL,
FOREIGN KEY (blog) REFERENCES Blog("id")
) STRICT;
CREATE TABLE Post_tags_Many (
"owner" BLOB NOT NULL,
has TEXT NOT NULL,
FOREIGN KEY ("owner") REFERENCES Post("id")
FOREIGN KEY (has) REFERENCES "Tag"("tag")
) STRICT;
CREATE TABLE Tag (
"tag" TEXT NOT NULL PRIMARY KEY
) STRICT;
CREATE TABLE IF NOT EXISTS butane_migrations (
"name" TEXT NOT NULL PRIMARY KEY
) STRICT;
