[package]
name = "newtype-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
butane = { workspace = true, features = ["sqlite"] }
json-patch = "1.2"
serde = "1.0"
serde_json = "1.0"

[package.metadata.release]
release = false
