CREATE TABLE a ("id" INTEGER NOT NULL PRIMARY KEY);
CREATE TABLE b ("id" INTEGER NOT NULL PRIMARY KEY);
CREATE TABLE b_many_a_Many (
    "owner" INTEGER NOT NULL,
    has INTEGER NOT NULL,
    FOREIGN KEY ("owner") REFERENCES b("id"),
    FOREIGN KEY (has) REFERENCES a("id")
);
