[package]
name = "butane_cli"
version = "0.5.1"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"
description = "The CLI for the Butane ORM"
readme = "../README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Electron100/butane"
documentation = "https://docs.rs/butane/"

[[bin]]
name = "butane"
path = "src/main.rs"

[features]
sqlite-bundled = ["butane/sqlite-bundled"]

[dependencies]
anyhow = "1.0"
butane = { path = "../butane", version = "0.5", features = [
  "default",
  "pg",
  "sqlite",
] }
chrono = { version = "0.4", default-features = false }
clap = { version = "4.1" }
quote = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = "1.0"
