[package]
name = "butane_cli"
version.workspace = true
authors = ["James Oakley <james@electronstudio.org>"]
edition.workspace = true
description = "The CLI for the Butane ORM"
readme = "../README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Electron100/butane"
documentation = "https://docs.rs/butane/"

[lib]
doc = false

[[bin]]
name = "butane"
path = "src/main.rs"
doc = false

[features]
sqlite-bundled = ["butane/sqlite-bundled"]

[dependencies]
anyhow = "1.0"
butane = { features = ["default", "pg", "sqlite"], workspace = true }
cargo_metadata = "0.17"
chrono = { workspace = true }
clap = { version = "4.1", features = ["string"] }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
