[package]
name = "butane_cli"
version = "0.6.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"
description = "The CLI for the Butane ORM"
readme = "../README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Electron100/butane"
documentation = "https://docs.rs/butane/"

[lib]
doc = false

[[bin]]
name = "butane"
path = "src/main.rs"

[features]
sqlite-bundled = ["butane/sqlite-bundled"]

[dependencies]
anyhow = "1.0"
butane = { features = ["default", "pg", "sqlite"], workspace = true }
chrono = { workspace = true }
clap = { version = "4.1" }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
