[package]
name = "butane_cli"
version = "0.5.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"
description = "The CLI for the Butane ORM"
readme = "../README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Electron100/butane"
documentation = "https://docs.rs/butane/"

[[bin]]
name = "butane"
path = "src/main.rs"

[features]
sqlite-bundled = ["butane/sqlite-bundled"]

[dependencies]
anyhow = "1.0"
butane = { path="../butane", version="0.5", features=["default", "sqlite", "pg"] }
chrono = "0.4"
clap = "2.33"
quote = "1.0"
serde = "1.0"
serde_json = "1.0"