CREATE TABLE Post (
`id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
title TEXT NOT NULL,
body TEXT NOT NULL,
published BOOLEAN NOT NULL,
byline VARCHAR(255)
);
ALTER TABLE Post ADD CONSTRAINT Post_byline_fkey FOREIGN KEY (byline) REFERENCES `User`(`id`);
