CREATE TABLE Patches (
id INTEGER NOT NULL PRIMARY KEY,
patch TEXT NOT NULL
);
CREATE TABLE Record (
id INTEGER NOT NULL PRIMARY KEY,
patch TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS butane_migrations (
"name" TEXT NOT NULL PRIMARY KEY
);