[package]
name = "butane_core"
version = "0.5.0"
authors = ["James Oakley <james@electronstudio.org>"]
edition = "2018"
description = "Internals for Butane. Do not use this crate directly -- use the butane crate."
readme = "../README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Electron100/butane"


[features]
datetime = ["chrono"]
debug = ["log"]
sqlite = ["rusqlite"]
sqlite-bundled = ["rusqlite/bundled"]
tls = ["postgres-native-tls", "native-tls"]
pg = ["tokio-postgres", "bytes"]


[dependencies]
bytes = { version="1.0", optional=true}
cfg-if = "1.0"
fallible-iterator = "0.2"
fallible-streaming-iterator = "0.1"
fs2 = "0.4" # for file locks
hex = "0.4"
once_cell="1.5"
log = { version="0.4", optional=true }
native-tls={ version = "0.2", optional = true }
tokio-postgres={ version = "0.7", features=["with-chrono-0_4"], optional = true}
postgres-native-tls={ version = "0.5", optional = true }
proc-macro2 = "1.0"
pin-project = "1"
quote = "1.0"
regex = "1.5"
r2d2 = {version="0.8", optional=true}
rusqlite = {workspace=true, optional = true}
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
thiserror = "1.0"
chrono = { version = "0.4", features=["serde"], optional = true }
uuid = {workspace=true, optional=true}
async-trait = "0.1"
